### ISSUE TITLE
Issue when opening blade tag when positioned beside double quote

### ISSUE THREAD

**Issue by haxzorer** [austenc/vscode-blade-spacer#1]
Hi!

First of all, nice work with the extension!

However, when using it today, I found a small bug. The extension has trouble with the "selection range" (I think is the right term), when opening a blade tag when the cursor is positioned right beside a double quote ("). I'll attach a gif below, showing the issue. The issue also seems to be happening when using single quotes (').

![laravel-blade-spacer-bug](https://user-images.githubusercontent.com/11200663/38664046-c9ae5d42-3e38-11e8-9f1e-10a0fa635a90.gif)

**Comment by austenc** [comment]
@haxzorer Thanks for reporting this issue. Hope to have it fixed soon. Cheers!

**Comment by austenc** [comment]
Looks like this is related to https://github.com/Microsoft/vscode/issues/35197 -- I may be able to put in a workaround for now though.

**Comment by haxzorer** [comment]
@austenc Awesome work, the latest release seems to have fixed it! 😄
