### ISSUE TITLE
Doesn't work when cursor is directly before a `<` character

### ISSUE THREAD

**Issue by mattlibera** [austenc/vscode-blade-spacer#10]
Not sure if this is related to a VS Code setting or not, but I couldn't find one that made a difference.

When the cursor directly precedes a `<` character (such as in a closing HTML tag) the Blade snippets do not trigger. Here is a quick illustration of what I've noticed, reproducible without any other extensions:
![2020-01-21_14-22-03](https://user-images.githubusercontent.com/6657359/72836157-16796880-3c5a-11ea-9e44-07931653d317.gif)

My use case is that I use Emmet to generate a tag grouping, and then fill it in with HTML / Blade. (I would hazard a guess that my use case isn't that uncommon.) If I add whitespace between my cursor and the `<` character, then the Blade snippets trigger just fine.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by mattlibera** [comment]
Note that I've also discovered that this happens with single- and double-quotes as well - if the cursor immediately precedes one of these characters, the expansion of Blade snippets fails.

**Comment by austenc** [comment]
Hello @mattlibera and thank you for opening this issue! I noticed similar behavior in the quotes too, but luckily this should be an easy fix for you too. There is a vs code setting for **Auto Closing Brackets**. The default is `languageDefined`, but changing that to `always` should fix the quotes at least. Would you mind trying it out and letting me know?

<img width="438" alt="image" src="https://user-images.githubusercontent.com/575421/72862858-d7fca180-3c8b-11ea-8009-ef86a8259809.png">

**Comment by mattlibera** [comment]
@austenc Ahh, yes that does work. I apologize - I read over previous issues etc. but apparently missed where you referenced this - it's even in your release notes (pointing to https://github.com/microsoft/vscode/issues/35197)

Although I still wonder how this got changed on me - it was working just fine before. Perhaps during a recent upgrade to VSCode they changed this default or something...not sure. Oh well.

Anyway, thanks for the reply, and for the package!

**Comment by austenc** [comment]
@mattlibera Actually it is a result of me changing how this extension works. Previously it would listen / activate on _any event_, whereas now it only activates on certain content changed events. So prior to version 2+ it would bypass the vscode bracket setting!

This tripped me up too, but I feel it's better to respect the vscode settings than to have the extension reach further than it should. Perhaps I will put something in the readme calling out this setting specifically. 

Thank you for updating and closing the issue, and please do let me know if you run into anything else! Cheers!
