### ISSUE TITLE
Sometimes regex is greedy

### ISSUE THREAD

**Issue by austenc** [austenc/vscode-blade-spacer#11]
Weird stuff happens when you type `{{` in these sorts of cases, `|` represents the cursor:
```
|{{ $something }}
```

or

```
<a href="|">{{ $thing }}</a>
```

**Comment by mattlibera** [comment]
I was just going to report on this as well! These are the exact same two cases I came across.

**Comment by isaacfennell** [comment]
I get issues when typing either `-` or `{` anywhere between after the first `p` and before the first `{` in the following example:

`<p class="">{!! $content !!}</p><p class=""></p>`

**Comment by SharakPL** [comment]
This extension doesn't work if there's any character after `{{` other than space or new line:

![lrvl](https://user-images.githubusercontent.com/5007456/78181827-48325b00-7465-11ea-90a6-290dc3ba26b3.gif)

Workaround - update your _settings.json_ with this:
```
"[blade]": {
    "editor.autoClosingBrackets": "always",
}

**Comment by austenc** [comment]
@SharakPL see #6 -- although I like the idea of scoping it to blade files even better. Will see if we can add the settings you mentioned to the extension itself. Hope to have a release out soon to fix that and the greedy regex.

**Comment by SharakPL** [comment]
Default value of this property in VSCode is `languageDefined` so I think it's best to keep it that way. Also there should be info about it in readme since it's required for this extension to work properly.

**Comment by austenc** [comment]
@SharakPL thanks for your comments today. Turns out we can add the blade specific `autoClosingBrackets` as a default setting to this extension itself! 

I'll be publishing an update with this change and a fix for the regex momentarily. Once you update to that version you should be able to remove the snippet you added to settings.json.

**Comment by SharakPL** [comment]
Just wondering: why did you also change it for `[html]`?

**Comment by austenc** [comment]
@mattlibera @isaacfennell Are your issues resolved by the latest version? If not please reopen this issue or open a new one, thank you!

@SharakPL Great question! This was to support other templating languages, such as Handlebars or Statamic's [Antlers](https://docs.statamic.com/antlers). These languages often use an HTML file extension.

**Comment by mattlibera** [comment]
@austenc The original issue here is resolved with the cases you provided, but the case that @isaacfennell raised is still a problem. I'll open a new issue for it.
