### ISSUE TITLE
Unexpected behavior when cursor is between quotes and before unescaped data

### ISSUE THREAD

**Issue by mattlibera** [austenc/vscode-blade-spacer#14]
In a scenario outlined by @isaacfennell in #11, unexpected or incorrect expansion occurs when the cursor is before unescaped Blade content (i.e. using `{!! $var !!}` syntax).

In a few test cases, I have found that this is triggered by several characters, including `-`, `!`, and `{`. (There may be more but these are the most relevant, since they are all of the characters used in Blade tags.)

Examples of bad behavior:
![2020-04-02_09-20-13 (1)](https://user-images.githubusercontent.com/6657359/78254563-1dc3ba80-74c4-11ea-9b46-74da6fe07ffd.gif)

Note that this does not happen with normal escaped Blade content:
![2020-04-02_09-22-47 (1)](https://user-images.githubusercontent.com/6657359/78254593-2916e600-74c4-11ea-80df-c447a2433da9.gif)

So that you don't have to watch the GIF over and over...in these cases, when the cursor `|` is here: `<p class="|">{!! $content !!}</p><p class=""></p>`
1. inserting a string containing a dash (like `mt-`) will result in `<p class={!! "mt- !!}">` with `"mt-` highlighted
2. starting with only a dash will result in `<p clas{!! s="- !!}">` with `s="-` highlighted
3. starting with `!` will result in `<p class{!! ="" !!}>` with `=""` highlighted
4. starting with `{` will result in `<p class={!! "" !!}>` with `""` highlighted

**Comment by isaacfennell** [comment]
Wow, thanks for looking into this so thoroughly @mattlibera ! Gold star for you

**Comment by austenc** [comment]
Thank you to both of you! I'll make sure this gets fixed today.

**Comment by mattlibera** [comment]
Awesome, glad I could give back a little! Sorry I couldn't offer a PR. One of these days I'll get into writing plugins (and/or better at regex)...

**Comment by austenc** [comment]
@mattlibera @isaacfennell This should be fixed in the latest version (2.1.1) 🎉 

Cheers!

**Comment by mattlibera** [comment]
Sweet! Just installed 2.1.2 and all the cases mentioned here are addressed. Thank you for the quick fix!!
