### ISSUE TITLE
Comment Issue

### ISSUE THREAD

**Issue by enescakir** [austenc/vscode-blade-spacer#2]
Thanks for the great extension 🚀

When I clicked already commented text at blade files, it tries to close these brackets.
It's a little bit annoying behavior.

![comment1](https://user-images.githubusercontent.com/993199/38866548-e1904e60-4249-11e8-85b8-b59982e19b08.jpg)
(Exactly end of the first two brackets)
![comment2](https://user-images.githubusercontent.com/993199/38866549-e1b0895a-4249-11e8-9f27-79ce1c512735.jpg)

![comment3](https://user-images.githubusercontent.com/993199/38866550-e267da38-4249-11e8-869a-040b205016dc.jpg)

**Comment by austenc** [comment]
@EnesCakir 

This update should be available from the extension marketplace within the next hour or so (sometimes it takes a little while). Thanks for reporting this bug!
