### ISSUE TITLE
Cursor not centered in blade template tag when using vscodevim extension

### ISSUE THREAD

**Issue by ZayRTun** [austenc/vscode-blade-spacer#23]
I googled a lot about this issue and I couldn't find a solution.

The issue occurs when inserting blade template tags, while using vscodevim extension. If i disable the vim extension it works perfectly.

Sorry I didn't want to be a pain in the ass. I love using this extension and also vim. And it just annoys me to see that cursor sticking to the right whenever I insert a template tag.

Please advice and shed some light onto how I can go about fixing this damn bug.
![Screenshot from 2021-12-16 08-44-03](https://user-images.githubusercontent.com/31787822/146394427-58879975-548c-441d-92d0-0b12b0b7e12a.png)

**Comment by austenc** [comment]
Hmm, that's strange. Guessing both extensions are trying to manipulate the selection at the same time and one of them (likely vim) is winning out. 

I don't use the official vim extension, but feel free to submit a PR to this repo if you figure out how to fix it!

In the meantime, you may try using https://marketplace.visualstudio.com/items?itemName=auiworks.amvim extension. My experience is that this one works much better than the other one. Hopefully it works for you!
