### ISSUE TITLE
Support for Twig {% and {#

### ISSUE THREAD

**Issue by mrleblanc101** [austenc/vscode-blade-spacer#24]
Would be nice to add support to expand `{%` to `{% | %}` and `{#` to `{# | #}` in Twig files

**Comment by austenc** [comment]
I'm open to adding this if you want to make a PR for it!

**Comment by AbhinavNmdo** [comment]
Pls, close this

**Comment by mrleblanc101** [comment]
There is a small issue with `{%`, the spaces are not added.
![2023-12-19 11 08 48](https://github.com/austenc/vscode-blade-spacer/assets/17392251/ec7d5467-876e-49df-8214-0c67c1637572)

**Comment by mrleblanc101** [comment]
The issue came from [Twig braces helper](https://github.com/zepich/twig-braces-helper) which was conflicting.

**Comment by austenc** [comment]
Thanks @mrleblanc101 @AbhinavNmdo both for the contribution to this discussion! Stoked to have support for this in the extension now!
