### ISSUE TITLE
Can't touch start blades with out end blades.

### ISSUE THREAD

**Issue by gojirian** [austenc/vscode-blade-spacer#3]
if for example you have removed the end blades.  then your cursor touches the start blades. it will recreate the end blades. 
So if you have backspaced the line. it will never let you delete them.
![image](https://user-images.githubusercontent.com/4308070/44563642-27971f00-a7b3-11e8-8bb7-d621dd84deea.png)
![image](https://user-images.githubusercontent.com/4308070/44563649-2d8d0000-a7b3-11e8-8dea-d5aaabe9cada.png)

**Comment by austenc** [comment]
Hi there @nat- and thank you for reporting this issue. I'll try to look into this soon, but not quite sure how I would fix it. Happy to take a PR for it if you have ideas!

**Comment by gojirian** [comment]
I am not 100% sure, but looking through what you've got it looks like it's always listening on all events , can you limit it to run the script only on key presses of the '{', '!' and '-' keys?

**Comment by ctf0** [comment]
same here ex.`{{$test}}` putting the cursor next to the opening braces `{{` will auto add ` }}` even when the closing braces are already present.

**Comment by austenc** [comment]
I've been encountering this too. Have some ideas on how we might fix this
in the next version. I'll see what I can do!

**Comment by austenc** [comment]
Hi there @nathollings, @ctf0 -- this should be fixed in the latest version.

**Comment by bangkarim** [comment]
> if for example you have removed the end blades. then your cursor touches the start blades. it will recreate the end blades.
> So if you have backspaced the line. it will never let you delete them.
> ![image](https://user-images.githubusercontent.com/4308070/44563642-27971f00-a7b3-11e8-8bb7-d621dd84deea.png)
> ![image](https://user-images.githubusercontent.com/4308070/44563649-2d8d0000-a7b3-11e8-8dea-d5aaabe9cada.png)

halo..may i know how to make this symbo; {{-- --}}
