### ISSUE TITLE
Ignore .svelte files

### ISSUE THREAD

**Issue by j-n-f** [austenc/vscode-blade-spacer#30]
I ran into an issue where some of the completions created by this plugin interfered with a Svelte project I was working on (https://github.com/sveltejs/language-tools/issues/2274).

In Svelte there is special syntax like:

```svelte
{#if ...}
{/if}
```

This plugin will take `{#` and turn it into `{# | #}` (where `|` is the cursor position after autocomplete).

Unless there is a good reason to do this in files with a `.svelte` suffix, I would recommend:

1. Constraining the extension to work on files that would be in a Laravel project, or
2. At least ignore `.svelte` files

I imagine there will probably be other frameworks/template languages which use `{#`, so the first option would allow this plugin to co-exist peacefully with those as well.

**Comment by austenc** [comment]
Thanks for letting me know about this @j-n-f !

https://github.com/austenc/vscode-blade-spacer?tab=readme-ov-file#twig-templating

I've added a setting to allow disabling of Twig templating support. At some point I'd like to add improved support so the plugin only works with specific languages, but this should work for you for now. It will be up on the VSCode Marketplace in a few minutes, cheers!
