### ISSUE TITLE
Issue when I place the cursor to the right of the laravel tag when there is no space between it is the variable

### ISSUE THREAD

**Issue by patrickmaciel** [austenc/vscode-blade-spacer#4]
Sorry for my english.
The gif below shows the problem.
![Screen Recording 2019-07-11 at 06 05 26 92 PM](https://user-images.githubusercontent.com/671670/61085768-6fdd2100-a407-11e9-9a7b-95db1bf09321.gif)

**Comment by austenc** [comment]
Thank you for reporting the issue! I've noticed this one as well. I've got some ideas of how to rewrite the extension to better handle this, will see what I can do!

**Comment by patrickmaciel** [comment]
@austenc thanks man :) This extension helps a lot!

**Comment by NoOorZ24** [comment]
I'm also waiting for this to be fixed.
This seems like a small problem but it's a nightmare to try to work with code that someone else wrote with no correct spacing

**Comment by austenc** [comment]
Turns out handling this is tricky and will require me to rewrite the entire extension. Working on it and hope to have it released this week (I'm close!)

**Comment by austenc** [comment]
@patrickmaciel @NoOorZ24 Should be fixed in the latest version, thank you!
