### ISSUE TITLE
Doesn't work inside quotes consistently

### ISSUE THREAD

**Issue by austenc** [austenc/vscode-blade-spacer#6]
inside quotes (such as an html tag parameter) it doesn't work right unless you select some text first.

Broken: `something="|"`
Working: `something="test|" (word `test` is selected)

**Comment by austenc** [comment]
![image](https://user-images.githubusercontent.com/575421/71861203-d1c6cc80-30b2-11ea-9dca-fd9647cc6268.png)
Nevermind, just a setting in vscode! The other sensible option is language-dependent and not something this extension needs to consider.

**Comment by jeffsuto** [comment]
thanks, it works
