### ISSUE TITLE
Problem when adding a comment to an existing var

### ISSUE THREAD

**Issue by gsabater** [austenc/vscode-blade-spacer#7]
Looks like a new bug has appeared.
I don't know on other scenarios, but when I try to add a comment on an existing bracket, the var is replaced completelly with a single ` - `

See gif for a demo, on this demo I just set the cursor on the start and just press `-` one and two times
![demo](https://user-images.githubusercontent.com/4948172/71969561-309d5a80-3207-11ea-9229-0e493e8abc97.gif)

Thanks

**Comment by austenc** [comment]
Aha! I'm seeing this too. Will try to get a fix out today for you. 

Edit: Forgot to thank you for reporting, thanks!
