### ISSUE TITLE
Version 2.* - conflict with intelephense + broken spacing in blade files

### ISSUE THREAD

**Issue by Corind7** [austenc/vscode-blade-spacer#8]
Hello,

with version 2.* there's issue that conflict with intelephense - intelephense showing errors on classes that have no errors.

It's described on link below and when your plugin is dowgraded to 1.*, issue disappears.
https://github.com/bmewburn/vscode-intelephense/issues/944

Also what I noticed is that in blade files when I type {{ inside html element it doesn't make end pair and breaks element indent (usually it is indented one or tab to left). When I downgraded to 1.*, this issued also disappeared.

**Comment by austenc** [comment]
@Corind7 

Thank you for opening the issue! I have seen this pop up a few times too. Looks like I'll be rewriting the extension yet again 👍.

**Comment by austenc** [comment]
@Corind7 this should be fixed in the latest version (`2.0.2`) of the plugin. Sorry to all the folks who've been putting up with this for over a week. 😅 

Please reopen if it continues to be an issue for you!
